resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/12.yaml

packages:
  - .

extra-deps:
  - git: git@github.com:silky/wai-middleware-auth.git
    commit: 0fd52ef057eed2607de622329dff234c1898fc2b
